# Serverless Framework Configuration
# This file tells AWS how to deploy your API
# Perfect for beginners to understand serverless deployment

service: booking-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-north-1'}
  apiName: booking-api-axile
  
  environment:
    BOOKINGS_TABLE: hotel-bookings-axile
  
  # IAM permissions for DynamoDB access
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.BOOKINGS_TABLE}"

# Define your API endpoints
functions:
  # Create a new booking
  createBooking:
    handler: functions/CreateBooking/handler.handler
    events:
      - http:
          path: /bookings
          method: post
          cors: true

  # Get all bookings
  getAllBookings:
    handler: functions/GetAllBookings/handler.handler
    events:
      - http:
          path: /bookings
          method: get
          cors: true

  # Get a specific booking by ID
  getBooking:
    handler: functions/GetBooking/handler.handler
    events:
      - http:
          path: /bookings/{id}
          method: get
          cors: true

  # Update a booking
  updateBooking:
    handler: functions/UpdateBooking/handler.handler
    events:
      - http:
          path: /bookings/{id}
          method: put
          cors: true

  # Delete a booking
  deleteBooking:
    handler: functions/DeleteBooking/handler.handler
    events:
      - http:
          path: /bookings/{id}
          method: delete
          cors: true

# AWS Resources (DynamoDB table)
resources:
  Resources:
    BookingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: hotel-bookings-axile
        AttributeDefinitions:
          - AttributeName: bookingId
            AttributeType: S
        KeySchema:
          - AttributeName: bookingId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

# Development plugins
plugins:
  - serverless-offline